# Generated by Django 4.2.1 on 2025-06-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predmeti",
            name="horario",
        ),
    ]
