# Generated by Django 4.2.1 on 2025-06-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_predmeti_horario"),
    ]

    operations = [
        migrations.AddField(
            model_name="predmeti",
            name="horario",
            field=models.CharField(
                blank=True,
                help_text="Formato libre, e.g. 'Lun 8:00-10:00; Mié 14:00-16:00'",
                max_length=100,
                null=True,
            ),
        ),
    ]
